version: '3.1'

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.9.1
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      - ./orthancDB/:/var/lib/orthanc/db/
    secrets:
      - orthanc.json
secrets:
  orthanc.json:
    file: orthanc.json
