version: '3.1'

services:
# nginx
  nginx:
    image: 'nginx:stable'
    ports: 
      - 80:80
      - 443:443
    volumes:  
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      # Volumes we need for TLS / certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - orthanc
    restart: always

# Certbot
  certbot:
    image: certbot/certbot
    volumes:
      - /home/sip/sip/confNGINX:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# status page
  status:
    image: php:7.3.0-apache
    volumes:
      - ../status:/var/www/html
    restart: always
  

# PostgreSQL Database
  postgres:
    image: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - /home/sip/sip/postgresDB/:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: "keycloak,orthanc,sipapi"
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: MyS3cureP@55!!
    restart: always


#keycloak
  keycloak:
    image: jboss/keycloak:12.0.3
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: administrator
      DB_SCHEMA: public
      DB_PASSWORD: MyS3cureP@55!!
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "k3YS4s3cur1ty!"
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - postgres
    restart: always



# Orthanc
  orthanc:
    image: jodogne/orthanc-plugins:1.9.1
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    secrets:
      - orthanc.json
    depends_on:
      - postgres
    restart: always


#  # API
#  #- docker run --name=sip_api --restart always -p 8081:8081 -dit cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipapi
  api:
    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipapi
    restart: always
    depends_on:
      - postgres


# REACT
  react:
    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipreact
    volumes:
      - '../sip-react:/app'
      - '/home/sip/sip/react/Pictures:/app/public/Pictures'
      - '/home/sip/sip/react/node_modules:/app/node_modules'
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true


# Database Loader
#- docker run --name=sip_dataloader --restart always -dit cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipdataloader
  databaseloader:
    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipdatabaseloader
    restart: always
    depends_on:
      - postgres
    volumes:
      - '/home/sip/sip/react/Pictures:/var/lib/sip-react/Pictures'

# Orthanc configuration
secrets:
  orthanc.json:
    file: ./orthanc.json
