version: '3.1'

services:
# nginx
  nginx:
    container_name: dev-nginx
    ports:
      - 8085:80
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    image: 'nginx:latest'
    network_mode: "host"
    depends_on:
      - orthanc
    restart: always


# PostgreSQL Database
  postgres:
    image: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgresDB/:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: "keycloak,orthanc,sipapi"
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: MyS3cureP@55!!
    ports:
      - 5432:5432
    restart: always


#keycloak
  keycloak:
    image: jboss/keycloak:12.0.3
    volumes: 
      - ./keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: administrator
      DB_SCHEMA: public
      DB_PASSWORD: MyS3cureP@55!!
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: "k3YS4s3cur1ty!"
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always



# Orthanc
  orthanc:
    image: jodogne/orthanc-plugins:1.9.1
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    depends_on:
      - postgres
    restart: always


#  # API
#  #- docker run --name=sip_api --restart always -p 8081:8081 -dit cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipapi
#  api:
#    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipapi
#    ports:
#      - 8081:8081
#    restart: always
#    depends_on:
#      - postgres
#
#
#  # REACT
#  react:
#    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipreact
#    ports:
#      - 3000:3000
#    restart: always
#    depends_on:
#      - postgres
#
#  # Database Loader
#  #- docker run --name=sip_dataloader --restart always -dit cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipdataloader
#  databaseloader:
#    image: cr.gitlab.fhnw.ch/b-ls-mi-sip/projects-2021/sip2021-01-sth/sipdatabaseloader
#    restart: always
#    depends_on:
#      - postgres

# Orthanc configuration
secrets:
  orthanc.json:
    file: ./orthanc.json
