version: '3'

services:
  keycloakDB:
      image: postgres
      volumes:
        - ./keycloakDB/:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

        
  keycloak:
      image: jboss/keycloak:12.0.3
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloakDB
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        DB_PORT: 5432
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8080:8080
      depends_on:
        - keycloakDB
