server:
  port: 8081

keycloak:
  realm: FHNW-LST-MI
  auth-server-url: http://localhost/auth
  resource: rest-api
  bearer-only: true
  enabled: true

spring:
  datasource:
    password: MyS3cureP@55!!
    url: jdbc:postgresql://localhost:5432/sipapi
    username: administrator
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true