server:
  port: 8081

keycloak:
  realm: FHNW-LST-MI
  auth-server-url: http://localhost:8080/auth
  resource: rest-api
  bearer-only: true
  enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sipapi
    username: sip
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true