image: maven:3.6-openjdk-11
stages:
  - test
  - build

test:
  stage: test
  script:
    - mvn clean test

build:
  stage: build
  script: mvn --batch-mode package
  artifacts:
     paths:
        - ./target/*.jar
