image: maven:3.6-openjdk-11
stages:
  - test
  - build
  - run

test:
  stage: test
  script:
    - mvn clean test

build:
  stage: build
  script: mvn --batch-mode package
  artifacts:
     paths:
        - ./target/*.jar

run:
  stage: run
  script: ./sip-api/src/main/java/ch/fhnw/lst/sipapi/SpitalprojektApplication.java
